on:
  push:
    branches:
    - main
    - develop
    
jobs:
  build:
    name: Deploy Flow
    runs-on: ubuntu-latest
    steps:

     - name: Sets env vars for production
       run: echo "DEPLOY_ENVIRONMENT=production" >> $GITHUB_ENV
       if: github.ref == 'refs/heads/main'

     - name: Sets env vars for production
       run: echo "DEPLOY_ENVIRONMENT=development" >> $GITHUB_ENV
       if: github.ref == 'refs/heads/develop'

     - name: Checkout
       uses: actions/checkout@v3
        
     - name: Update pip
       run: python3 -m pip install --upgrade pip

     - name: Upgrade pyOpenSSL and cryptography
       run: python3 -m pip install -U pyOpenSSL cryptography
        
     - name: Install requirements
       run: pip3 install -r requirements.txt
        
     - name: Login to Prefect
       run: prefect cloud login -k ${{ secrets.PREFECT_API_KEY }} -w caredesign/${{ env.DEPLOY_ENVIRONMENT }}
        
    #  - name: Run tests
    #    run: pytest tests/

     - name: Deploy to Prefect
       run: python3 deploy.py
    



